### ISSUE TITLE
issue on running cloudypad cli

### ISSUE THREAD

**Issue by dchhouen** [PierreBeucher/cloudypad#13]
I ran the curl command to install curl -fsSL https://raw.githubusercontent.com/PierreBeucher/cloudypad/master/install.sh | sh , but i do not see any values after running cloudypad create or cloudypad -v 

It seems like the install.sh ran fine.

See below images. 

![image](https://github.com/user-attachments/assets/01207b18-899a-425b-a6ec-85010ab98b79)

![image](https://github.com/user-attachments/assets/62cb5049-222e-403e-a5e9-f0f885d6a794)

**Comment by dchhouen** [comment]
i am running Linux Mint 21 
![image](https://github.com/user-attachments/assets/66074a40-7645-4edf-ae14-5c0ba7f911db)

**Comment by PierreBeucher** [comment]
Hi, wwhat do you see when running `cloudypad --version` ? Can you try to run

```
cloudypad create -v 0
```

(will run with high verbosity)

I'll try to run a VM with Linux Mint to reproduce, thanks for these details

**Comment by PierreBeucher** [comment]
Should  be fixed by https://github.com/PierreBeucher/cloudypad/pull/14

**Comment by dchhouen** [comment]
Tried to reinstall with the new update but it looks like I'm still having an issue .

steps ran

```shell
rm -rf ~/.cloudypad
curl -fsSL https://raw.githubusercontent.com/PierreBeucher/cloudypad/master/install.sh | sh
closed terminal and re-opened new terminal
cloudypad create -v 0 # no output was seen .

```

**Comment by PierreBeucher** [comment]
:facepalm: I didn't make a new release so the fix wasn't available sorry. Incoming.

**Comment by PierreBeucher** [comment]
Can you try again? If you encounter another issue, open script at `~/.cloudypad/bin/cloudypad` and append `set -x` right after `#!/usr/bin/env bash` such as:

```
#!/usr/bin/env bash

set -x
```

To get more debug information.

**Comment by dchhouen** [comment]
perfect, i'm able to get it running.

Separate question:
For credentials on aws, is it retrieving it from reading a file or pulling from the current terminal session? It seems like it is doing some variant of the former. I did an env override in the current terminal session for aws creds , but it look like it just used the default credentials configurations.

**Comment by PierreBeucher** [comment]
Great ! Thanks for your encouragements, such feedbacks are greatly appreciated :)

In short, (almost) everything runs in a container. For AWS `~/.aws` is mounted by default, but currently host env variables such as `AWS_*` are not passed into container. I'm working on this via https://github.com/PierreBeucher/cloudypad/pull/18/commits/d4ee54c7e9fc93fc843198d3329e26056fd22655#diff-f435ce60719c9393e09e4d69d5311169c31832772fe42623d9957b08dbefff40 to allow for simple use case like using a profile (`AWS_PROFILE`) or directly using credentials via `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. Though some use cases may not be possible yet (like having AWS creds in non-standard location) it should be a good starting point.
